/* This file is autogenerated, do not edit*/
#include "moc_TelescopeControl.cpp"
#include "moc_TelescopeClient.cpp"
#include "moc_TelescopeClientDirectLx200.cpp"
#include "moc_TelescopeClientDirectNexStar.cpp"
#include "moc_SlewDialog.cpp"
#include "moc_TelescopeConfigurationDialog.cpp"
#include "moc_TelescopeDialog.cpp"
