/* This file is autogenerated, do not edit*/
#include "moc_CCD.cpp"
#include "moc_Lens.cpp"
#include "moc_Ocular.cpp"
#include "moc_Oculars.cpp"
#include "moc_Telescope.cpp"
#include "moc_OcularDialog.cpp"
#include "moc_OcularsGuiPanel.cpp"
#include "moc_PropertyBasedTableModel.cpp"
