/* This file is autogenerated, do not edit*/
#include "moc_Satellites.cpp"
#include "moc_SatellitesListFilterModel.cpp"
#include "moc_SatellitesListModel.cpp"
#include "moc_SatellitesDialog.cpp"
#include "moc_SatellitesImportDialog.cpp"
